# This is a basic workflow to help you get started with Actions

name: Dataroma Scraper

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [push, windows-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

            
      - uses: actions/setup-node@v3
        with:
          node-version: 16
            
      # Runs a set of commands using the runners shell
      - name: Launching
        run: |
            ./launch.bat

      - name: Save the generated files
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
